# Generated by Django 5.0.2 on 2024-02-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0002_name_alter_place_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Place1',
        ),
    ]
