# Generated by Django 5.0.2 on 2024-02-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0003_rename_name_place1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place1',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='place1',
            old_name='name',
            new_name='name1',
        ),
    ]
