# Generated by Django 5.0.2 on 2024-02-20 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0004_rename_desc_place1_desc1_rename_name_place1_name1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place1',
        ),
    ]
